config/routes.rb
Rails.application.routes.draw do
  resources :songs
  devise_for :users
  resources :comments
  resources :song_users
  resources :followers
  
  devise_scope :user do 
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :comments
  get 'feed', to: 'comments#index', as: :feed
  root 'songs#index'

  get '/profile/:id', to: 'profiles#show', as: 'profile'
  post '/favourites', to: 'favourites#create'

  

end






  # as :user do 
  #   get '/register', to: 'devise/registrations#new', as: :register
  #   get '/login', to: 'devise/sessions#new', as: :login
  #   get '/logout', to: 'devise/sessions#destroy', as: :logout
  # end

  # devise_for :users, skip: [:sessions]

  # as :user do 
  #  get "/login" => "devise/sessions#new", as: :new_user_session
  #  post "/login" => "deivse/sessions#create", as: :new_user_session
  #  delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  # end


  # resources :user_followers
  

  # resources :comments
  # get 'feed', to: 'comments#index', as: :feed
  # root 'comments#index'

  # get '/:id', to: 'profiles#show', as: 'profile'
  

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @comments = @user.comments.all
    @songs = @user.songs.all
    @follower = Follower.new
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class='page-header'>
  <h1><%= @user.full_name %></h1>  
    <%  if @user.id != current_user.id %>
    <%= simple_form_for(@follower) do |f| %>
    <%= f.hidden_field :friend_id, value: @user.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.button :submit, class: "btn btn-success" %>
    <% end %>
    <% end %>
</div>

<div class="row-fluid">
 <div class="span12">
    <div class="span3">
      <%= image_tag @user.user_image.url, class: "large-user-image"  %>
      <hr />
      <p>About:</p>
      <%= @user.email %>
    </div>
    <div class="span7">
    <h2>Uploads</h2>
      <% if @songs  %>
        <% @songs.each do |song| %>
        <div class='well'>
          <%= song.artist %>  
          <hr />
          <%= audio_tag song.sound_file, autoplay: false, controls: true  %>
          <hr />
          <%= link_to song.title, song_path(song) %>
        </div>
         <% end %>
         <% end %>
        <h3>Favourites</h3>
        <% @user.favourites.each do |d|  %>
        <div class='well'>
          <%= image_tag d.song.song_image, class: 'favourite_image' %>
          <%= link_to d.song.title, song_path(d.song.id)  %>
        </div>  
        <% end  %>    
        <% if @comments %> 
        <h3>Comments</h3>
         <% @comments.each do |comment|  %>
        <div class='well'>
          <%= comment.content %>     
          <hr />
          <%= link_to comment.song.title, song_path(comment.song.id) %> |    
          <%= link_to time_ago_in_words(comment.created_at), comment_path(comment) %>   

        </div>  
          <% end  %>
          <% end %>   
        </div>  
     <div class="span2">
      <h2>Friends</h1>
      <% @user.followers.each do |f| %>
      <div class='well'>
      <%= link_to f.friend.full_name, profile_path(f.friend.id) %> 
      <hr />
      <%= image_tag f.friend.user_image, class: 'friend_image' %>
      </div>  
      <% end  %>
     </div>     
  </div>
</div>




                  