config/routes.rb
Rails.application.routes.draw do
  resources :songs
  devise_for :users
  resources :comments
  resources :song_users
  resources :followers
  
  devise_scope :user do 
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :comments
  get 'feed', to: 'comments#index', as: :feed
  root 'songs#index'

  get '/profile/:id', to: 'profiles#show', as: 'profile'
  post '/favourites', to: 'favourites#create'

  

end






  # as :user do 
  #   get '/register', to: 'devise/registrations#new', as: :register
  #   get '/login', to: 'devise/sessions#new', as: :login
  #   get '/logout', to: 'devise/sessions#destroy', as: :logout
  # end

  # devise_for :users, skip: [:sessions]

  # as :user do 
  #  get "/login" => "devise/sessions#new", as: :new_user_session
  #  post "/login" => "deivse/sessions#create", as: :new_user_session
  #  delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  # end


  # resources :user_followers
  

  # resources :comments
  # get 'feed', to: 'comments#index', as: :feed
  # root 'comments#index'

  # get '/:id', to: 'profiles#show', as: 'profile'
  

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :favourites

  mount_uploader :sound_file, SoundFileUploader
  mount_uploader :song_image, SongImageUploader
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = Song.all
  end

  def show
    @comment = Comment.new
    @favourite = Favourite.new
  end

  def new
    @song = Song.new
  end

  def edit
  end

  def create
    @song = current_user.songs.new(song_params)
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:title, :artist, :length, :url, :user_id, :sound_file, :song_image)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= simple_form_for(@song) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.text_field :title, :placeholder => "Title" %>
    <%= f.text_field :artist, :placeholder => "Artist" %>
    <%= f.label :sound_file %>
    <%= f.file_field :sound_file, :placeholder => "Upload Song" %>
    <%= f.label :sound_image %>
    <%= f.file_field :song_image, :placeholder => "Upload Image" %>   
  </div>
  <div class="form-actions">
   <%= f.submit 'Upload' %>
  </div>
  <% end  %>

    

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<div class="page-header">
  <h1>All Songs</h1>
  <%= link_to 'Upload Song', new_song_path, class: "btn btn-success" %>
</div>

<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span8">        
        <table>
          <tbody>
            <% @songs.each do |song| %>
            <div class='song_index'>            
               <%= link_to song.title, song_path(song) %>
               <%= song.artist %>
               <%= song.length %>          
               <%= link_to(song.user.full_name, profile_path(song.user.id)) %>
               <span class='admin'>
                <%= link_to 'Show', song %>
                <%= link_to 'Edit', edit_song_path(song) %>
                <%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %>  
              </span>
              </div>
                <% end %>
          </tbody>
        </table>
          </div>
            <div class="span2 offset2">
          <h2>Friends</h1>
      </div>
    </div>
  </div>
</div>

<br>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<div class='page-header'>
  <h2><%= @song.artist %>  | <%= @song.title %></h2>
</div>

<div class='well'>
 <%= image_tag @song.song_image.url, class: 'song_image' %>
 <%= audio_tag @song.sound_file, autoplay: false, controls: true  %>
 <strong><%= @song.title %></strong>  
 <%= @song.artist %>
</div>
<div class='well button-well'>
  <%= simple_form_for(@favourite) do |f| %>
  <%= f.hidden_field :song_id, value: params[:id] %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Like", class: "btn btn-success" %> 
  <% end %>
  
  <p>Likes: <%= @song.favourites.count %> </p>
</div>
<%= render partial: 'comments/form' %>
<% @song.comments.each do |c| %>
<div class='well'>
  <%= image_tag c.user.user_image, class: 'comment_image' %>
  <%= c.user.full_name %> | 
  <%= c.content %>  
</div>
<% end %>
<%#= image_tag @song.song_image %>
<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>