config/routes.rb
Rails.application.routes.draw do
  resources :songs
  devise_for :users
  resources :comments
  resources :song_users
  resources :followers
  
  devise_scope :user do 
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :comments
  get 'feed', to: 'comments#index', as: :feed
  root 'songs#index'

  get '/profile/:id', to: 'profiles#show', as: 'profile'
  post '/favourites', to: 'favourites#create'

  

end






  # as :user do 
  #   get '/register', to: 'devise/registrations#new', as: :register
  #   get '/login', to: 'devise/sessions#new', as: :login
  #   get '/logout', to: 'devise/sessions#destroy', as: :logout
  # end

  # devise_for :users, skip: [:sessions]

  # as :user do 
  #  get "/login" => "devise/sessions#new", as: :new_user_session
  #  post "/login" => "deivse/sessions#create", as: :new_user_session
  #  delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  # end


  # resources :user_followers
  

  # resources :comments
  # get 'feed', to: 'comments#index', as: :feed
  # root 'comments#index'

  # get '/:id', to: 'profiles#show', as: 'profile'
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BpmApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='navbar navbar-fixed-top'>
 <div class='navbar-inner'>
   <div class='container'>
   <%= link_to '120BPM', songs_path, class: 'brand' %>
    <ul class='nav'>
      <li><%= link_to "All Comments", feed_path %></li>
      <li><%= link_to "All Songs", songs_path %></li>
    </ul>    
     <ul class='nav pull-right'>      
          <% if user_signed_in? %> 
          <% user = current_user.id  %>
          <li><%= link_to current_user.full_name, profile_path(user) %></li>
          <li><%= link_to('Logout', logout_path) %></li> 
          <% else %>
          <li><%= link_to('Login', login_path) %></li>         
          <li><%= link_to('Sign up', register_path)  %></li>
          <% end %>        
        </ul>
    </ul>
   </div>
 </div> 
</div>

<div class='container'>
    <% if flash[:notice]  %>
      <div class='alert alert-success'>
        <button class='close' data-dismiss='alert'>x</button>
          <%= flash[:notice] %>        
      </div>
      <% end  %>

      <% if flash[:alert]  %>
      <div class='alert alert-error'>
        <button class='close' data-dismiss='alert'>x</button>
          <%= flash[:alert] %>
      </div>
    <% end  %>
 <%= yield %>

</div>
</body>
</html>